# Generated by Django 2.2.17 on 2020-11-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('tagline', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
