version: '3.7'

services:
    proxy:
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        volumes: 
            - static_volume:/usr/src/app/static
            - media_volume:/usr/src/app/media
        ports: 
            - "80:80"
        depends_on: 
            - webapp 
        restart: "on-failure"
    webapp:
        build: 
            context: .
            dockerfile: Dockerfile
        command: sh -c "python manage.py flush --no-input && python manage.py migrate_schemas && python manage.py new_tenant && gunicorn api.wsgi:application --bind 0.0.0.0:8000"
        volumes: 
            - static_volume:/usr/src/app/static
            - media_volume:/usr/src/app/media
        expose: 
            - 8000
        env_file: 
            - ./.env
        depends_on: 
            - db
        restart: "on-failure"
    db:
        image: postgres:13.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment: 
            - POSTGRES_PASSWORD=welcome@1
            - POSTGRES_DB=dbtesting
            - POSTGRES_USER=victor
        restart: "on-failure"
                
   
volumes: 
    static_volume:
    postgres_data:
    media_volume:
