# Generated by Django 2.2.17 on 2020-12-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('status', models.CharField(max_length=10)),
                ('txn_date', models.DateTimeField(auto_now_add=True)),
                ('ref', models.CharField(max_length=256)),
                ('cutomer_id', models.CharField(max_length=256)),
                ('cutomer_f_name', models.CharField(max_length=256)),
                ('cutomer_l_name', models.CharField(max_length=256)),
                ('customer_email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['txn_date'],
            },
        ),
    ]
