# Generated by Django 2.2.17 on 2020-12-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
