# Generated by Django 2.2.17 on 2020-11-25 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201125_0259'),
        ('cart', '0002_auto_20201119_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item_variation',
        ),
        migrations.AddField(
            model_name='cart',
            name='item_variation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.ProductVariation'),
            preserve_default=False,
        ),
    ]
