# Generated by Django 2.2.17 on 2020-11-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20201125_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item_variation',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
