# Generated by Django 2.2.17 on 2020-12-02 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=126)),
                ('unpaid', models.BooleanField(default=0)),
                ('paid', models.BooleanField(default=0)),
                ('cancelled', models.BooleanField(default=0)),
                ('opened', models.BooleanField(default=0)),
                ('shipping_cost', models.IntegerField(default=0)),
                ('total_cost', models.IntegerField(default=0)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
                ('customer_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
