# Generated by Django 2.2.17 on 2020-11-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='cancelled',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='opened',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='paid',
            field=models.BooleanField(default=0),
        ),
    ]
