# Generated by Django 2.2.17 on 2020-11-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201125_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='shipping_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='unpaid',
            field=models.BooleanField(default=0),
        ),
    ]
