# Generated by Django 2.2.17 on 2020-11-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoption',
            name='product',
        ),
        migrations.RemoveField(
            model_name='products',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='products',
            name='quantity_in_stock',
        ),
        migrations.RemoveField(
            model_name='products',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='products',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='quantity',
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default=0, upload_to='product_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='variation',
            field=models.ManyToManyField(to='products.ProductVariation'),
        ),
    ]
