# Generated by Django 2.2.17 on 2020-11-30 10:51

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='variation',
        ),
        migrations.AddField(
            model_name='products',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='quantity_in_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='PNG', keep_meta=True, quality=75, size=[312, 312], upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='PNG', keep_meta=True, quality=75, size=[312, 312], upload_to='product_images'),
        ),
    ]
