# Generated by Django 2.2.17 on 2020-11-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='variation',
            field=models.ManyToManyField(related_name='product_variations', to='products.ProductVariation'),
        ),
    ]
