# Generated by Django 2.2.17 on 2020-11-30 16:11

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201130_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[312, 312], upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[312, 312], upload_to='product_images'),
        ),
    ]
